name: CI and CD
on: 
  push:
    branches:
      - source
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git config --global user.email "vinsensius.danny@gmail.com"
      - run: git config --global user.name "Vinsensius Danny"
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run build
      - run: npm run deploy
      # - name: Deploy
      #   uses: crazy-max/ghaction-github-pages@v1
      #   with:
      #     target_branch: source
      #     build_dir: public
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}